#!/bin/sh

HISTFILE=$HOME/.zsh_history
setopt appendhistory

HISTSIZE=1000000
SAVEHIST=1000000

export PATH="$HOME/.local/bin":$PATH
export PATH="$PATH:$HOME/.npm/bin"

export KUBECONFIG=$HOME/.config/kube/config

export MANPAGER='nvim +Man!'
export MANWIDTH=999
export CLICOLOR=1

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


eval "$(zoxide init zsh)"
eval "$(/usr/local/bin/brew shellenv)"


