#!/bin/sh

HISTFILE=$HOME/.zsh_history
setopt appendhistory

HISTSIZE=1000000
SAVEHIST=1000000

export PATH="$HOME/.local/bin":$PATH
export PATH="$PATH:$HOME/.npm/bin"

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. /usr/share/LS_COLORS/dircolors.sh


eval "$(zoxide init zsh)"

# disable background color
eval "$(dircolors -p | \
    sed 's/ 4[0-9];/ 01;/; s/;4[0-9];/;01;/g; s/;4[0-9] /;01 /' | \
    dircolors /dev/stdin)"

