#!/usr/bin/zsh
# This is the entry file for login scripts
# Init nvm
echo 0 >$HOME/.nvm/nvm.state
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
echo 1 >$HOME/.nvm/nvm.state
